import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#FCC332',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cercle: {
    width: 400,
    height: 400,
    // backgroundColor: 'red',
    // position: 'absolute',
    // zIndex: 1,
    borderRadius: 400,
    alignSelf: 'center',
    marginTop: '30%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    paddingHorizontal: 20,
    alignSelf: 'center',
  },
  circle: {
    width: 150,
    height: 150,
    backgroundColor: '#c00000',
    borderRadius: 100,
  },
  first: {
    width: 130,
    height: 130,
    backgroundColor: 'white',
    borderRadius: 130,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    // marginTop: '50%',
    borderLeftWidth: 5,
    borderRightWidth: 10,
    borderBottomWidth: 2,
  },
  two: {
    width: 130,
    height: 130,
    backgroundColor: 'white',
    borderRadius: 130,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    top: '0%',
    position: 'absolute',
    borderLeftWidth: 5,
    borderRightWidth: 10,
    borderBottomWidth: 2,
  },
  three: {
    width: 130,
    height: 130,
    backgroundColor: 'white',
    borderRadius: 130,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    top: '23%',
    right: '2%',
    borderLeftWidth: 5,
    borderRightWidth: 10,
    borderBottomWidth: 2,
    position: 'absolute',
  },
  four: {
    width: 130,
    height: 130,
    backgroundColor: 'white',
    borderRadius: 130,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    top: '58%',
    right: '10%',
    borderLeftWidth: 5,
    borderRightWidth: 10,
    borderBottomWidth: 2,
    position: 'absolute',
  },
  five: {
    width: 130,
    height: 130,
    backgroundColor: 'white',
    borderRadius: 130,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    top: '60%',
    right: '55%',
    borderLeftWidth: 5,
    borderRightWidth: 10,
    borderBottomWidth: 2,
    position: 'absolute',
  },
  six: {
    width: 130,
    height: 130,
    backgroundColor: 'white',
    borderRadius: 130,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: '45%',
    right: '65%',
    borderLeftWidth: 5,
    borderRightWidth: 10,
    borderBottomWidth: 2,
    position: 'absolute',
  },
});
